// Local tests only. This module is not reachable from either Worker entry point.
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from './review.mjs';
import {digest} from './partner-auth.mjs';
export const origin='https://review.example';
export function fixture(){
  const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');
  for(const name of ['schema.sql','partners-schema.sql'])sql.exec(readFileSync(new URL(name,import.meta.url),'utf8'));
  const DB={prepare(query){const statement=sql.prepare(query);let params=[];return {bind(...values){params=values;return this},async first(){return statement.get(...params)||null},async all(){return {results:statement.all(...params)}},async run(){return {meta:{changes:Number(statement.run(...params).changes)}}}}},async batch(statements){sql.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};
  const env={DB,PARTNER_BASE_URL:origin+'/',GOOGLE_CLIENT_ID:'public-client',GOOGLE_CLIENT_SECRET:'google-private-secret',SESSION_SECRET:'test-private-session-secret',REVIEWER_EMAILS:'owner@example.com',GITHUB_OWNER:'owner',GITHUB_REPO:'poems',GITHUB_TOKEN:'private-github-token',PUBLIC_SITE_URL:'https://poems.example/'};
  const files={'data/authors.json':[{id:'a',name:'作者甲',aliases:['作者甲','甲'],bio:'',tags:[],link:''},{id:'b',name:'作者乙',aliases:['作者乙'],bio:'',tags:[],link:''}],'data/poems.json':[{id:'p1',title:'旧诗',author:'作者甲',content:'公开正文',date:'2026-09-30',series:'拾遗记',images:['images/old.jpg'],extra:'keep'},{id:'p2',title:'另一人',author:'作者乙',content:'另一首',date:'2026-09-30',series:'拾遗记',images:[]}]};
  const version={'data/authors.json':1,'data/poems.json':1};let writes=0,conflictOnce=false;let google={sub:'google-person',email:'person@example.com',email_verified:true};
  const previous=globalThis.fetch;
  globalThis.fetch=async (input,options={})=>{const url=String(input);if(url==='https://oauth2.googleapis.com/token'){const params=new URLSearchParams(options.body);if(params.get('client_secret')!==env.GOOGLE_CLIENT_SECRET)throw new Error('bad test secret');return Response.json({access_token:'google-temporary-token'})}if(url==='https://openidconnect.googleapis.com/v1/userinfo'){if(options.headers.authorization!=='Bearer google-temporary-token')throw new Error('bad bearer');return Response.json(google)}const match=url.match(/\/contents\/(data\/[^?]+\.json)$/);if(!match)throw new Error('unexpected fetch '+url);const path=match[1];if(options.headers.authorization!=='Bearer '+env.GITHUB_TOKEN)throw new Error('github secret mismatch');if(options.method==='PUT'){const data=JSON.parse(options.body);if(conflictOnce){conflictOnce=false;version[path]++;return Response.json({}, {status:409})}if(data.sha!==String(version[path]))return Response.json({}, {status:409});files[path]=JSON.parse(Buffer.from(data.content,'base64').toString());version[path]++;writes++;return Response.json({content:{sha:String(version[path])}})}return Response.json({sha:String(version[path]),content:Buffer.from(JSON.stringify(files[path])).toString('base64')})};
  async function person(id='u1',status='active',author='a'){const now=new Date().toISOString();sql.prepare('INSERT INTO partners (id,google_sub,email,status,author_id,desired_name,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').run(id,'sub-'+id,id+'@example.com',status,author,id==='u1'?'作者甲':'作者乙',now,now);const token=id==='u1'?'a'.repeat(64):'b'.repeat(64);sql.prepare('INSERT INTO partner_sessions (session_hash,partner_id,expires_at,created_at) VALUES (?,?,?,?)').run(await digest(token),id,new Date(Date.now()+86400000).toISOString(),now);return token}
  async function call(path,method='GET',data,{token='a'.repeat(64),admin=false,headers={}}={}){const req=new Request(origin+path,{method,headers:{Origin:origin,'X-Requested-With':admin?'poem-review':'poem-partner','CF-Connecting-IP':'192.0.2.1',Cookie:'__Host-poem_partner='+token,...(data!==undefined?{'Content-Type':'application/json'}:{}),...headers},...(data!==undefined?{body:JSON.stringify(data)}:{})});return worker.fetch(req,env,admin?{access:{getIdentity:async()=>({email:'owner@example.com'})}}:{} )}
  return {sql,DB,env,files,version,person,call,get writes(){return writes},set google(value){google=value},conflict(){conflictOnce=true},close(){globalThis.fetch=previous;sql.close()}};
}
