import test from 'node:test';
import assert from 'node:assert/strict';
import {Script} from 'node:vm';
import {fixture,origin} from './partners-fixture.mjs';
import {cleanupPartnerData,digest} from './partner-auth.mjs';
import {partnerPage} from './partner-ui.mjs';
const props={title:'新诗',content:'第一行\n第二行',date:'2026-10-02',series:'拾遗记',subseries:''};
async function ok(response,status=200){assert.equal(response.status,status,await response.clone().text());return response.json()}
async function work(f){const r=await ok(await f.call('/api/partners/works','POST',props),201);return (await ok(await f.call('/api/partners/works/'+r.id))).work}
async function own(f){f.sql.prepare('INSERT INTO partner_poems VALUES (?,?,?,?)').run('p1','u1','a',new Date().toISOString());return ok(await f.call('/api/partners/poems/p1'))}
test('Google authorization requires a one-time cookie-bound state and verified provider identity',async()=>{const f=fixture();try{let res=await f.call('/partner-auth/login');assert.equal(res.status,303);let url=new URL(res.headers.get('location')),state=url.searchParams.get('state');assert.equal(url.searchParams.get('scope'),'openid email');assert.equal(url.searchParams.get('redirect_uri'),origin+'/partner-auth/callback');let cookie='__Host-poem_partner_state='+state;
assert.equal((await f.call('/partner-auth/callback?code=x&state='+state,'GET',undefined,{headers:{Cookie:''}})).status,403);
res=await f.call('/partner-auth/callback?code=x&state='+state,'GET',undefined,{headers:{Cookie:cookie}});assert.equal(res.status,303);const row=f.sql.prepare('SELECT * FROM partners').get();assert.equal(row.status,'new');assert.equal(row.google_sub,'google-person');assert.match(res.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);assert.ok(!res.headers.get('set-cookie').includes('google-temporary-token'));assert.equal((await f.call('/partner-auth/callback?code=x&state='+state,'GET',undefined,{headers:{Cookie:cookie}})).status,403);
f.google={sub:'google-person',email:'changed@example.com',email_verified:true};res=await f.call('/partner-auth/login');state=new URL(res.headers.get('location')).searchParams.get('state');await f.call('/partner-auth/callback?code=x&state='+state,'GET',undefined,{headers:{Cookie:'__Host-poem_partner_state='+state}});assert.equal(f.sql.prepare('SELECT count(*) AS n FROM partners').get().n,1);assert.equal(f.sql.prepare('SELECT email FROM partners').get().email,'changed@example.com');
f.google={sub:'another',email:'other@example.com',email_verified:false};res=await f.call('/partner-auth/login');state=new URL(res.headers.get('location')).searchParams.get('state');assert.equal((await f.call('/partner-auth/callback?code=x&state='+state,'GET',undefined,{headers:{Cookie:'__Host-poem_partner_state='+state}})).status,403);assert.equal(f.sql.prepare('SELECT count(*) AS n FROM partners').get().n,1);
}finally{f.close()}});
test('anonymous, pending and other accounts cannot acquire creator or maintainer privileges',async()=>{const f=fixture();try{assert.equal((await f.call('/api/partners/me')).status,401);await f.person('u1','pending','');assert.equal((await f.call('/api/partners/works','POST',props)).status,403);assert.equal((await f.call('/api/collaborators')).status,403);await f.person('u2','active','b');let res=await ok(await f.call('/api/partners/works','POST',props,{token:'b'.repeat(64)}),201);f.sql.prepare("UPDATE partners SET status='active',author_id='a' WHERE id='u1'").run();assert.equal((await f.call('/api/partners/works/'+res.id)).status,404);assert.equal((await f.call('/api/partners/poems/p2')).status,404);assert.equal((await f.call('/api/partners/works','POST',props,{headers:{Origin:'https://evil.example'}})).status,403);assert.equal((await f.call('/api/partners/works','POST',props,{headers:{'X-Requested-With':''}})).status,403);const me=await ok(await f.call('/api/partners/me'));assert.ok(!JSON.stringify(me).includes('google_sub'));}finally{f.close()}});
test('maintainer must bind identity explicitly; historical assignment is bounded and suspension revokes sessions',async()=>{const f=fixture();try{await f.person('u1','pending','');let person=f.sql.prepare("SELECT * FROM partners WHERE id='u1'").get();assert.equal((await f.call('/api/collaborators/u1/approve','POST',{updatedAt:person.updated_at,poemIds:[]},{admin:true})).status,409);assert.equal((await f.call('/api/collaborators/u1/approve','POST',{updatedAt:person.updated_at,authorId:'a',poemIds:['p2']},{admin:true})).status,409);await ok(await f.call('/api/collaborators/u1/approve','POST',{updatedAt:person.updated_at,authorId:'a',poemIds:[]},{admin:true}));assert.equal(f.sql.prepare('SELECT count(*) AS n FROM partner_poems').get().n,0);person=f.sql.prepare("SELECT * FROM partners WHERE id='u1'").get();await ok(await f.call('/api/collaborators/u1/assign','POST',{updatedAt:person.updated_at,poemIds:['p1']},{admin:true}));assert.equal(f.sql.prepare('SELECT partner_id FROM partner_poems').get().partner_id,'u1');person=f.sql.prepare("SELECT * FROM partners WHERE id='u1'").get();await ok(await f.call('/api/collaborators/u1/suspend','POST',{updatedAt:person.updated_at},{admin:true}));assert.equal((await f.call('/api/partners/me')).status,401);assert.equal(f.sql.prepare('SELECT count(*) AS n FROM partner_sessions').get().n,0);}finally{f.close()}});
test('draft versions, initial review and publication retain ownership; stale maintainer actions fail',async()=>{const f=fixture();try{await f.person();let w=await work(f);for(let i=0;i<12;i++){await ok(await f.call('/api/partners/works/'+w.id,'PUT',{...props,title:'版本'+i,version:w.version}));w=(await ok(await f.call('/api/partners/works/'+w.id))).work}assert.equal(f.sql.prepare('SELECT count(*) AS n FROM partner_work_history').get().n,10);assert.equal((await f.call('/api/partners/works/'+w.id,'PUT',{...props,version:1})).status,409);assert.equal((await f.call('/api/partners/works/'+w.id+'/submit','POST',{version:w.version})).status,400);await ok(await f.call('/api/partners/works/'+w.id+'/submit','POST',{version:w.version,consent:true}));w=(await ok(await f.call('/api/partners/works/'+w.id))).work;const sid=w.submission_id,old=w.submissionUpdatedAt;
await ok(await f.call('/api/partners/works/'+w.id,'PUT',{...props,title:'最后一版',version:w.version,submissionUpdatedAt:old}));const admin={...props,title:'审核旧版',author:'作者甲',authorId:'a',expectedUpdatedAt:old};for(const [path,method,body]of [['','PUT',admin],['/publish','POST',{expectedUpdatedAt:old}],['/decline','POST',{expectedUpdatedAt:old}]])assert.equal((await f.call('/api/submissions/'+sid+path,method,body,{admin:true})).status,409);
w=(await ok(await f.call('/api/partners/works/'+w.id))).work;let saved=await ok(await f.call('/api/submissions/'+sid,'PUT',{...admin,title:w.title,expectedUpdatedAt:w.submissionUpdatedAt},{admin:true}));await ok(await f.call('/api/submissions/'+sid+'/publish','POST',{expectedUpdatedAt:saved.updatedAt},{admin:true}));const ownership=f.sql.prepare('SELECT * FROM partner_poems').get();assert.equal(ownership.partner_id,'u1');assert.equal(f.files['data/poems.json'].at(-1).title,'最后一版');const count=f.files['data/poems.json'].length;await ok(await f.call('/api/submissions/'+sid+'/publish','POST',{},{admin:true}));assert.equal(f.files['data/poems.json'].length,count);assert.equal((await f.call('/api/partners/works/'+w.id,'PUT',{...props,version:w.version,submissionUpdatedAt:w.submissionUpdatedAt})).status,409);
}finally{f.close()}});
test('profile writes only approved fields of the bound author, with SHA checks',async()=>{const f=fixture();try{await f.person();const {sha}=await ok(await f.call('/api/partners/profile'));assert.equal((await f.call('/api/partners/profile','PUT',{sha,name:'冒名',bio:'',tags:[],link:''})).status,403);assert.equal((await f.call('/api/partners/profile','PUT',{sha,bio:'简介',tags:[],link:'javascript:alert(1)'})).status,400);await ok(await f.call('/api/partners/profile','PUT',{sha,bio:'简介',tags:['诗'],link:'https://example.com'}));assert.equal(f.files['data/authors.json'][0].bio,'简介');assert.equal(f.files['data/authors.json'][1].bio,'');assert.equal((await f.call('/api/partners/profile','PUT',{sha,bio:'旧页覆盖',tags:[],link:''})).status,409);}finally{f.close()}});
test('published revisions remain private until version-matched approval, preserving metadata and images',async()=>{const f=fixture();try{await f.person();let view=await own(f);await ok(await f.call('/api/partners/poems/p1/revision','PUT',{...props,version:0,baseHash:view.baseHash,submit:true}));assert.equal(f.writes,0);assert.equal(f.files['data/poems.json'][0].title,'旧诗');view=await ok(await f.call('/api/partners/poems/p1'));const rev=view.revision;await ok(await f.call('/api/partners/poems/p1/revision','PUT',{...props,title:'再改',version:rev.version,baseHash:rev.baseHash,submit:true}));assert.equal((await f.call('/api/revisions/'+rev.id+'/approve','POST',{version:rev.version},{admin:true})).status,409);assert.equal((await f.call('/api/revisions/'+rev.id+'/reject','POST',{version:rev.version},{admin:true})).status,409);view=await ok(await f.call('/api/partners/poems/p1'));f.conflict();await ok(await f.call('/api/revisions/'+rev.id+'/approve','POST',{version:view.revision.version},{admin:true}));const poem=f.files['data/poems.json'][0];assert.equal(poem.title,'再改');assert.equal(poem.author,'作者甲');assert.deepEqual(poem.images,['images/old.jpg']);assert.equal(poem.extra,'keep');assert.ok(poem.updatedAt);let n=f.writes;await ok(await f.call('/api/revisions/'+rev.id+'/approve','POST',{version:view.revision.version},{admin:true}));assert.equal(f.writes,n);
}finally{f.close()}});
test('public version conflicts require explicit rebase and re-submission; withdrawals never delete published poems',async()=>{const f=fixture();try{await f.person();let view=await own(f);await ok(await f.call('/api/partners/poems/p1/revision','PUT',{...props,version:0,baseHash:view.baseHash,submit:true}));view=await ok(await f.call('/api/partners/poems/p1'));f.files['data/poems.json'][0].content='维护者更改';assert.equal((await f.call('/api/revisions/'+view.revision.id+'/approve','POST',{version:view.revision.version},{admin:true})).status,409);assert.equal((await f.call('/api/partners/poems/p1/revision','PUT',{...props,version:view.revision.version,baseHash:view.revision.baseHash,submit:true})).status,409);await ok(await f.call('/api/partners/poems/p1/rebase','POST',{version:view.revision.version}));view=await ok(await f.call('/api/partners/poems/p1'));assert.equal(view.revision.status,'draft');assert.equal(view.revision.data.content,props.content);assert.equal((await f.call('/api/revisions/'+view.revision.id+'/approve','POST',{version:view.revision.version},{admin:true})).status,409);await ok(await f.call('/api/partners/poems/p1/withdraw','POST',{version:view.revision.version}));assert.equal(f.files['data/poems.json'][0].content,'维护者更改');}finally{f.close()}});
test('cleanup removes finished private copies even after ordinary submission rows have been removed',async()=>{const f=fixture();try{await f.person();let w=await work(f);await ok(await f.call('/api/partners/works/'+w.id,'PUT',{...props,version:w.version}));w=(await ok(await f.call('/api/partners/works/'+w.id))).work;await ok(await f.call('/api/partners/works/'+w.id+'/submit','POST',{version:w.version,consent:true}));w=(await ok(await f.call('/api/partners/works/'+w.id))).work;f.sql.prepare('DELETE FROM submissions WHERE id=?').run(w.submission_id);await cleanupPartnerData(f.env);assert.equal(f.sql.prepare('SELECT content FROM partner_works').get().content,'');assert.equal(f.sql.prepare('SELECT count(*) AS n FROM partner_work_history').get().n,0);}finally{f.close()}});
test('ownership changes stop old collaborators; deleting a draft also deletes private history',async()=>{const f=fixture();try{await f.person();await own(f);f.files['data/poems.json'][0].author='作者乙';assert.equal((await f.call('/api/partners/poems/p1')).status,409);let w=await work(f);await ok(await f.call('/api/partners/works/'+w.id,'PUT',{...props,version:w.version}));assert.equal((await f.call('/api/partners/works/'+w.id,'DELETE',{version:w.version})).status,409);await ok(await f.call('/api/partners/works/'+w.id,'DELETE',{version:w.version+1}));assert.equal(f.sql.prepare('SELECT count(*) AS n FROM partner_works').get().n,0);assert.equal(f.sql.prepare('SELECT count(*) AS n FROM partner_work_history').get().n,0);}finally{f.close()}});
test('bulk historical assignment uses a transactional claim and cannot overwrite a competing owner',async()=>{const f=fixture();try{await f.person('u1','pending','');await f.person('u2','active','b');for(let i=0;i<80;i++)f.files['data/poems.json'].push({...f.files['data/poems.json'][0],id:'old-'+i});const ids=f.files['data/poems.json'].filter(p=>p.author==='作者甲').map(p=>p.id);let person=f.sql.prepare("SELECT * FROM partners WHERE id='u1'").get();await ok(await f.call('/api/collaborators/u1/approve','POST',{updatedAt:person.updated_at,authorId:'a',poemIds:ids},{admin:true}));assert.equal(f.sql.prepare('SELECT count(*) AS n FROM partner_poems').get().n,81);
f.files['data/poems.json'].push({...f.files['data/poems.json'][0],id:'race'});person=f.sql.prepare("SELECT * FROM partners WHERE id='u1'").get();const originalBatch=f.DB.batch;f.DB.batch=async statements=>{f.sql.prepare('INSERT INTO partner_poems VALUES (?,?,?,?)').run('race','u2','b',new Date().toISOString());return originalBatch(statements)};assert.equal((await f.call('/api/collaborators/u1/assign','POST',{updatedAt:person.updated_at,poemIds:['race']},{admin:true})).status,502);assert.equal(f.sql.prepare("SELECT partner_id FROM partner_poems WHERE poem_id='race'").get().partner_id,'u2');assert.equal(f.sql.prepare("SELECT updated_at FROM partners WHERE id='u1'").get().updated_at,person.updated_at);
}finally{f.close()}});
test('pages have valid inline scripts, strict nonce CSP and no secrets',async()=>{const f=fixture();try{for(const mode of ['creator','members','revisions']){const res=partnerPage(mode,f.env),html=await res.text();const script=html.match(/<script nonce="[^"]+">([\s\S]*?)<\/script>/)[1];new Script(script);assert.match(res.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.ok(!html.includes(f.env.GOOGLE_CLIENT_SECRET));assert.ok(!html.includes(f.env.GITHUB_TOKEN));}Object.assign(f.env,{GITHUB_OAUTH_CLIENT_ID:'github-public-id',GITHUB_OAUTH_SECRET:'github-private-secret'});f.env.REVIEW_AUTH='github';assert.equal((await f.call('/collaborators')).status,200);assert.match(await (await f.call('/collaborators')).text(),/使用 GitHub 登录/);assert.equal((await f.call('/api/revisions')).status,401);}finally{f.close()}});
