export function securityPage(partner=false) {
  const nonce=crypto.randomUUID(),config=JSON.stringify({partner});
  return new Response(SECURITY_HTML.replaceAll('__NONCE__',nonce).replace('__CONFIG__',config),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','referrer-policy':'no-referrer','x-content-type-options':'nosniff','x-frame-options':'DENY','permissions-policy':'camera=(), microphone=(), geolocation=()','content-security-policy':`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'`}});
}
export const SECURITY_HTML=String.raw`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>账号安全 · 诗歌漂流</title><style nonce="__NONCE__">
:root{--paper:#f7f5f0;--sheet:#ede9e2;--ink:#2c2a28;--muted:#5a554e;--line:#d6ccbd;--gold:#b79b76;--clay:#9c4d32;--glass:rgba(247,245,240,.88);--serif:Georgia,"Noto Serif SC",serif;--sans:system-ui,"Noto Sans SC",sans-serif}
html[data-theme=dark]{--paper:#1e1e1c;--sheet:#292925;--ink:#ecece5;--muted:#bfbeb3;--line:#58574d;--gold:#d4a373;--clay:#ee9481;--glass:rgba(30,30,28,.9)}html[data-theme=eye]{--paper:#ecf3e5;--sheet:#e0e8d9;--ink:#3a4632;--muted:#505d46;--line:#b6c2a9;--gold:#977d47;--clay:#925336;--glass:rgba(236,243,229,.9)}
*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.65 var(--sans)}a{color:inherit;text-underline-offset:4px}button{font:inherit;color:inherit;cursor:pointer;border:1px solid var(--line);border-radius:999px;background:transparent;padding:9px 17px;min-height:44px}button:hover,a:hover{color:var(--clay)}button:disabled{opacity:.55;cursor:wait}.danger{color:var(--clay)}:focus-visible{outline:3px solid var(--gold);outline-offset:3px}header{background:var(--glass);backdrop-filter:blur(18px);border-bottom:1px solid var(--line);padding:17px max(24px,calc((100vw - 1000px)/2));display:flex;align-items:center;justify-content:space-between;gap:20px}header .brand{font:26px var(--serif);text-decoration:none;white-space:nowrap}header .brand span{color:var(--clay)}nav{display:flex;align-items:center;flex-wrap:wrap;gap:18px;font-size:14px}nav button{font-size:14px;padding:5px 12px}main{max-width:1000px;margin:auto;padding:44px 24px 80px}h1{font:normal clamp(34px,5vw,50px)/1.2 var(--serif);margin:0}h2{font:normal 28px/1.35 var(--serif);margin:0 0 12px}p{margin:12px 0;max-width:70ch}.muted,.meta{color:var(--muted)}.meta{font-size:14px;overflow-wrap:anywhere}.intro{display:flex;justify-content:space-between;gap:24px;align-items:center;margin-bottom:26px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:20px}.section{margin-top:40px;padding-top:28px;border-top:1px solid var(--line)}.session{display:flex;gap:20px;align-items:center;justify-content:space-between;padding:20px 0;border-bottom:1px solid var(--line)}.session strong{font-weight:600}.session p{margin:5px 0}.session button{flex-shrink:0}.tag{display:inline-block;margin-left:10px;padding:2px 9px;border:1px solid var(--line);border-radius:999px;font-size:13px}.message{margin:18px 0;overflow-wrap:anywhere}.message:empty{display:none}.error{color:var(--clay)}.event{display:grid;grid-template-columns:180px minmax(0,1fr) 85px;gap:18px;padding:17px 0;border-bottom:1px solid var(--line);align-items:start}.event p{margin:0;overflow-wrap:anywhere}.event code{font:14px/1.65 var(--sans);overflow-wrap:anywhere}.status{font-size:14px}#more{margin-top:20px}#pause-status{font-size:18px}.footer{margin-top:40px;color:var(--muted);font-size:14px}#login{display:inline-block;margin-top:10px}@media(max-width:640px){header{align-items:flex-start;flex-direction:column;gap:12px;padding:16px 20px}nav{gap:14px}main{padding:30px 20px 60px}.intro{align-items:flex-start;flex-direction:column;gap:12px}.section{margin-top:32px;padding-top:24px}.session{align-items:flex-start;flex-direction:column;gap:12px}.event{grid-template-columns:1fr;gap:6px}.actions button{flex-grow:1}.tag{margin-left:6px}}
</style></head><body><!-- Direction contract:
THESIS: account safety actions are visible beside the active login list; every action reports its result.
OWN-WORLD: inherit paper, ink, clay, serif headings, pill buttons and glass navigation from the protected workspace.
STORY: identify current and other logins, revoke unwanted access, then review submission availability and change records.
FIRST VIEWPORT: account safety heading, session list and explicit exit actions; maintainer controls follow in document order.
FORM: precise extension of existing account settings using rows and section dividers, no new visual identity.
FINISH: unreviewed and undocumented is unfinished; this build ends with the finish review, the verdict, and DESIGN.md
--><header><a class="brand" href="https://zhege712-crypto.github.io/Poem_Ulysses/">诗歌<span>漂流</span></a><nav><a id="back" href="/">返回工作台</a><button id="theme" type="button">切换主题</button></nav></header><main>
<div class="intro"><div><h1>账号安全</h1><p class="muted">查看登录会话，及时收回不再使用的访问权限。</p></div><button id="refresh" type="button">刷新记录</button></div>
<p id="notice" class="message" role="status" aria-live="polite"></p><a id="login" href="/auth/login?return=/security" target="_blank" rel="noopener" hidden>在新标签页重新确认登录</a>
<section aria-labelledby="session-heading"><h2 id="session-heading">登录会话</h2><p id="account" class="meta"></p><p class="muted">每次登录会形成一个会话，同一设备可能有多条记录。浏览器标签仅供参考，不保存完整设备信息或原始 IP。</p><div id="sessions" aria-busy="true"><p class="muted">正在读取登录记录…</p></div><p id="session-feedback" class="message error" role="status" aria-live="polite"></p><button id="session-retry" type="button" hidden>重试登录记录</button><div class="actions"><button id="others" type="button" disabled>退出其他会话</button><button id="all" class="danger" type="button" disabled>退出所有会话</button></div></section>
<section id="settings" class="section" aria-labelledby="settings-heading" hidden><h2 id="settings-heading">新投稿接收</h2><p id="pause-status">正在读取…</p><p class="muted">暂停后，新的普通投稿和合作伙伴首次送审暂不接收；已有稿件查询、撤回、草稿保存和审核继续可用。</p><button id="pause" type="button" disabled>读取设置中…</button><p id="settings-feedback" class="message error" role="status" aria-live="polite"></p><button id="settings-retry" type="button" hidden>重试接收设置</button></section>
<section id="audit" class="section" aria-labelledby="audit-heading" hidden><h2 id="audit-heading">最近操作</h2><p class="muted">保存最近 90 天的操作摘要，包含操作者、操作对象和结果。记录不包含稿件正文、联系方式或登录密钥。</p><div id="events"><p class="muted">正在读取操作记录…</p></div><p id="audit-feedback" class="message error" role="status" aria-live="polite"></p><button id="audit-retry" type="button" hidden>重试操作记录</button><button id="more" type="button" hidden>查看更早记录</button></section>
<p class="footer">退出会话不会删除诗稿。账号安全设置与作品编辑分开处理；在其他页面编辑时，请先保存草稿。</p>
</main><script nonce="__NONCE__">(function(){'use strict';
var cfg=__CONFIG__,prefix=cfg.partner?'/api/partners/security':'/api/security',busy=false,paused=false,settingsReady=false,next=null,rows=[];
var $=function(id){return document.getElementById(id)},node=function(tag,text,cls){var el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el},time=function(value){return new Date(value).toLocaleString('zh-CN',{hour12:false})};
function message(text,error){$('notice').textContent=text||'';$('notice').className='message'+(error?' error':'')}
async function api(path,method,data){var opt={method:method||'GET',credentials:'same-origin',headers:{'X-Requested-With':cfg.partner?'poem-partner':'poem-review'}};if(data!==undefined){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(data)}var response=await fetch(prefix+path,opt),result;try{result=await response.json()}catch{throw new Error('服务暂时无法读取，请稍后刷新')}if(!response.ok){if(response.status===401||result.code==='reauth_required')$('login').hidden=false;throw new Error(result.error||'操作未完成')}return result}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(function(b){b.disabled=true});try{await fn()}catch(e){message(e.message,true)}finally{busy=false;$('refresh').disabled=false;$('theme').disabled=false;$('others').disabled=!rows.some(function(s){return !s.current});$('all').disabled=!rows.length;$('pause').disabled=cfg.partner||!settingsReady;$('more').disabled=false;['session','settings','audit'].forEach(function(kind){$(kind+'-retry').disabled=false});document.querySelectorAll('[data-revoke]').forEach(function(b){b.disabled=false})}}
function sectionFeedback(kind,error){$(kind+'-feedback').textContent=error?error.message:'';$(kind+'-retry').hidden=!error}
async function sessionsLoad(){var box=$('sessions');box.setAttribute('aria-busy','true');try{var result=await api('/sessions');rows=result.sessions;$('account').textContent=(result.accountLabel||'')+' · '+(cfg.partner?'合作账号':'维护者账号');box.replaceChildren();if(!rows.length)box.append(node('p',result.managed?'没有有效的登录会话。':'当前通过访问网关登录，会话由网关管理。','muted'));rows.forEach(function(row){var section=node('div',undefined,'session'),copy=node('div'),heading=node('strong',row.browser);if(row.current)heading.append(node('span','当前会话','tag'));copy.append(heading,node('p','登录于 '+time(row.createdAt),'meta'),node('p','到期于 '+time(row.expiresAt),'meta'));var button=node('button',row.current?'退出当前会话':'退出此会话');button.type='button';button.dataset.revoke=row.id;button.onclick=function(){if(!confirm('确认退出'+(row.current?'当前':'此')+'登录会话？'))return;run(function(){return revoke({action:'revoke',id:row.id})})};section.append(copy,button);box.append(section)});sectionFeedback('session',null)}catch(e){rows=[];box.replaceChildren(node('p','登录记录未能加载。','muted'));sectionFeedback('session',e);throw e}finally{box.setAttribute('aria-busy','false')}}
async function refreshAfterAction(success,reads){message(success);var results=await Promise.allSettled(reads.map(function(read){return read()}));if(results.some(function(result){return result.status==='rejected'}))message(success+' 最新记录暂未加载，请使用对应的重试按钮刷新。',true)}
async function revoke(data){var result=await api('/sessions','POST',data);if(result.signedOut){location.href=cfg.partner?'/partners':'/';return}await refreshAfterAction('所选会话已退出。',cfg.partner?[sessionsLoad]:[sessionsLoad,function(){return auditLoad(false)}])}
async function settingsLoad(){$('settings').setAttribute('aria-busy','true');try{var data=await api('/settings');paused=data.submissionsPaused;settingsReady=true;$('pause-status').textContent=paused?'目前已暂停接收新投稿':'目前正常接收新投稿';$('pause-status').className=paused?'danger':'';$('pause').textContent=paused?'恢复接收新投稿':'暂停接收新投稿';sectionFeedback('settings',null)}catch(e){settingsReady=false;$('pause-status').textContent='暂时无法读取接收状态';$('pause-status').className='muted';$('pause').textContent='接收设置未加载';sectionFeedback('settings',e);throw e}finally{$('settings').setAttribute('aria-busy','false')}}
function describe(row){var target=row.target,parts=target.split('/'),last=parts[parts.length-1];
if(row.action==='LOGIN')return target==='partner-session'?'Google 登录':'GitHub 登录';
if(target==='auth/logout'||target==='partner-auth/logout')return '退出当前登录';
if(target.includes('security/sessions'))return '管理登录会话';if(target==='api/security/settings')return '更改新投稿接收设置';
if(target.startsWith('api/admin/files/'))return '保存'+({poems:'公开诗集',authors:'作者资料',logs:'漂流地点'})[last]+'数据';
if(target==='api/images')return '上传作品配图';
if(target.startsWith('api/collaborators/'))return ({approve:'开通合作权限',reject:'拒绝合作申请',suspend:'暂停合作权限',reactivate:'恢复合作权限',assign:'关联历史作品',recover:'恢复中断的开通'})[last]+' · '+parts[2];
if(target.startsWith('api/revisions/'))return (last==='approve'?'批准作品修订':last==='reject'?'退回作品修订':'处理作品修订')+' · '+parts[2];
if(target.startsWith('api/submissions/'))return (last==='publish'?'发表投稿':last==='decline'?'退回投稿':'编辑待审稿')+' · '+parts[2];
if(target.startsWith('api/partners/works'))return (row.action==='DELETE'?'删除草稿':last==='submit'?'送审诗稿':last==='withdraw'?'撤回诗稿':'保存草稿')+(parts[3]?' · '+parts[3]:'');
if(target==='api/partners/apply')return '提交合作申请';if(target.includes('profile'))return '保存作者资料';if(target.startsWith('api/partners/poems'))return '更新作品修订申请 · '+parts[3];if(target.startsWith('api/published-poems/'))return '编辑已发表作品 · '+parts[2];return '处理请求';}
async function auditLoad(append){var box=$('events');box.setAttribute('aria-busy','true');try{var data=await api('/audit'+(append&&next?'?before='+encodeURIComponent(next):''));if(!append)box.replaceChildren();if(!data.events.length&&!append)box.append(node('p','还没有操作记录。','muted'));data.events.forEach(function(row){var section=node('div',undefined,'event'),who=node('div'),what=node('div'),result=row.result===0?'结果未确认':row.result<300?'已完成':row.result<500?'未执行':'失败';who.append(node('p',time(row.created_at),'meta'),node('p',row.actor.startsWith('reviewer:')?'维护者 · '+row.actor.slice(9):'合作账号 · '+row.actor.replace(/^partner:/,''),'meta'));what.append(node('p',describe(row)));section.append(who,what,node('span',result,'status'+(row.result===0||row.result>=400?' danger':'')));box.append(section)});next=data.next;$('more').hidden=!next;sectionFeedback('audit',null)}catch(e){if(!append){box.replaceChildren(node('p','操作记录未能加载。','muted'));next=null;$('more').hidden=true}sectionFeedback('audit',e);throw e}finally{box.setAttribute('aria-busy','false')}}
async function load(){message('');var reads=cfg.partner?[sessionsLoad]:[sessionsLoad,settingsLoad,function(){return auditLoad(false)}];var results=await Promise.allSettled(reads.map(function(read){return read()}));if(results.some(function(result){return result.status==='rejected'}))message('部分记录未能加载，请使用对应的重试按钮。',true)}
$('settings').hidden=cfg.partner;$('audit').hidden=cfg.partner;$('login').hidden=cfg.partner;$('back').href=cfg.partner?'/partners':'/admin';$('login').href=cfg.partner?'/partner-auth/login':'/auth/login?return=/security';
$('refresh').onclick=function(){run(load)};$('others').onclick=function(){if(confirm('确认退出其他所有登录会话，保留当前会话？'))run(function(){return revoke({action:'others'})})};$('all').onclick=function(){if(confirm('确认退出所有会话？当前页面也会退出登录。'))run(function(){return revoke({action:'all'})})};$('pause').onclick=function(){if(confirm(paused?'确认恢复接收新投稿？':'确认暂停接收新投稿？已有稿件和草稿不会删除。'))run(async function(){await api('/settings','PUT',{submissionsPaused:!paused});await refreshAfterAction('投稿接收设置已更新。',[settingsLoad,function(){return auditLoad(false)}])})};$('more').onclick=function(){run(function(){return auditLoad(true)})};
['session','settings','audit'].forEach(function(kind){$(kind+'-retry').onclick=function(){run(async function(){await (kind==='session'?sessionsLoad:kind==='settings'?settingsLoad:function(){return auditLoad(false)})();message('相关记录已刷新。')})}});var themes=['light','dark','eye'],theme='light';try{theme=localStorage.getItem('theme')||'light'}catch{}if(!themes.includes(theme))theme='light';function paint(){document.documentElement.dataset.theme=theme;$('theme').textContent={light:'日间',dark:'夜间',eye:'护眼'}[theme]}paint();$('theme').onclick=function(){theme=themes[(themes.indexOf(theme)+1)%3];paint();try{localStorage.setItem('theme',theme)}catch{}};run(load);
})();</script></body></html>`;
